package brownshome.scriptwars.game;

import java.util.Arrays;

public class IDPool {
	/** The id at IDs[nextFreeIndex] is the next index to be allocated. */
	private final int[] freeIDs;
	private final int capacity;
	private int nextFreeIndex = 0;
	
	public IDPool(int capacity) {
		this.capacity = capacity;
		freeIDs = new int[capacity];
		Arrays.fill(freeIDs, -1);
	}
	
	public int request() throws OutOfIDsException {
		if(nextFreeIndex != freeIDs.length) {
			int ID = freeIDs[nextFreeIndex];
			
			if(ID == -1) {
				ID = nextFreeIndex;
				freeIDs[nextFreeIndex] = ID;
			}
			
			nextFreeIndex++;
			
			return ID;
		}
		
		throw new OutOfIDsException();
	}
	
	public boolean hasFreeIDs() {
		return nextFreeIndex != capacity;
	}
	
	public int poolSize() {
		return capacity;
	}

	/** x must be an ID previously generated by this ID pool */
	public void free(int x) {
		freeIDs[--nextFreeIndex] = x;
	}
}
